# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df129a8dc7756d1fd53888f9d621d7d7ed787806685691d5c39a84b37958043847b6213d5cd1bc46d6d37433ef466746c8f64874d395867a95c156b020069e5a
  db_user: jammy
  db_password: Ch#nge#123

test:
  secret_key_base: 935d8585f89affec408d07973d2b88b025b662e1ffb5500a488b6e87f00f7e96d2cdac2d334f1cbb41f4fb190d12a776bbb4d46dd3219a28c8fd4a84f16478c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
